language: node_js

branches:
  only:
    - master

node_js:
  - "8"

before_install:
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

install:
  - npm install -g surge
  - npm install --force-online

jobs:
  include:
    - stage: Deploy DEV
      if: type = pull_request
      env:
        - NODE_ENV=production
        - STAGE=development
      script:
        - npm install --only=dev --force-online
        - make deploy
    - stage: deploy PRO
      if: branch = master AND NOT type = pull_request
      env:
        - NODE_ENV=production
        - STAGE=production
      script:
        - npm install --only=dev --force-online
        - make deploy
