module.exports = {
  ADMINTEXT_TITLE: 'Administrar textos',
  ADMIN_EVALUATION: 'Administrar avaluacions',
  ADMIN_EVALUATIONS_QUALITY_TITLE: 'Avaluacions de la qualitat textual',
  ADMIN_EVALUATIONS_SKIP_TITLE: 'Textos saltats',
  ADMIN_EVALUATIONS_STUCTURE_TITLE: "Avaluacions de l'estructura dels textos",
  ADMIN_EVALUATIONS_TEXTS_WITHOUT_QUALITY_TITLE: 'Text sense avaluacions de qualitat', // eslint-disable-line
  ADMIN_TEXTS: 'Administrar textos',
  APP_NAME: 'UABTextHandler',
  CANVASTEXTO_STUDENT: 'Estudiant',
  HOME_ALERT_ERROR_TITLE: 'Alguns camps estan incomplets',
  HOME_BUTTON_QUALITY: 'Avaluar qualitat',
  HOME_BUTTON_STRUCTURE: 'Avaluar estructura',
  HOME_LOOKING_TEXTS: 'Buscant text per avaluar',
  HOME_NO_MORE_TEXTS: 'Ja no hi ha més textos per avaluar',
  HOME_QUESTIONS: 'Qüestionari',
  HOME_TEXT: 'Text',
  LAYOUT_EVALUATION_CANVAS_LOOKING_TEXTS: 'Buscant text per avaluar',
  LAYOUT_EVALUATION_QUIZ_BUTTON_SAVE: 'Desar + següent',
  LAYOUT_EVALUATION_QUIZ_BUTTON_SKIP: 'Saltar text',
  LOGGED_MENU_QUALITY_EVALUATION: 'Avaluar qualitat',
  LOGGED_MENU_STRUCTURE_EVALUATION: 'Avaluar estructura',
  QUALITY_ERROR_MSG: 'El text encara no té avaluació!',
  QUALITY_QUIZ_NUMBER_SELECTR_LABEL: 'Qualitat del text',
  QUALITY_QUIZ_OPTION_FIFTH_PRIMARY: '5è primària',
  QUALITY_QUIZ_OPTION_FOURTH_PRIMARY: '4t primària',
  QUALITY_QUIZ_OPTION_NARRATIVE: 'narratiu',
  QUALITY_QUIZ_OPTION_OPINION: 'argumentatiu',
  QUALITY_QUIZ_OPTION_SECOND_ESO: '2n ESO',
  QUALITY_QUIZ_OPTION_SECOND_PRIMARY: '2n primària',
  QUALITY_QUIZ_OPTION_SIXTH_PRIMARY: '6è primària',
  QUALITY_QUIZ_OPTION_THIRD_PRIMARY: '3r primària',
  QUALITY_QUIZ_SELECT_GENRE: 'Tria un gènere discursiu',
  QUALITY_QUIZ_SELECT_GRADE: 'Tria un nivell educatiu',
  QUIZ_CONCLUSION: 'Té connectors de conclusió?',
  QUIZ_END_CONCLUSION: 'Hi ha la conclusió?',
  QUIZ_END_TYPE_CONCLUSION: 'Especifica el tipus de conclusió',
  QUIZ_EXTENSIVE: 'extensiva',
  QUIZ_FREE_TEXT_HINT: '(opcional)',
  QUIZ_FREE_TEXT_LABEL: 'Comentari lliure',
  QUIZ_INTRODUCTION: 'Té una introducció?',
  QUIZ_OPINION: 'Té la opinió?',
  QUIZ_OPINION_CONECTOR: 'Té connectors de opinió?',
  QUIZ_OPINION_OTHER_TYPE: "Té connectors d'opinió d'un altre tipus?",
  QUIZ_OTHER_CONECTORS: 'Té altres connectors?',
  QUIZ_REASON: 'Raó',
  QUIZ_REASON_CONECTORS: 'Nombre de connectors de raó',
  QUIZ_REASON_EXPLICATION: "Nombre de connectors d'explicació",
  QUIZ_SYNTHETIC: 'sintètica',
  QUIZ_THESIS_REP: 'repeteix tesi/opinió',
  RADIOBUTTONGROUP_RADIO_NO: 'No',
  RADIOBUTTONGROUP_RADIO_YES: 'Sí',
  REASON_ADD_TYPE: 'Afegir una explicació',
  REASON_EVIDENCES: 'Evidèncias',
  REASON_EXAMPLE: 'Exemple',
  REASON_EXPERTS: 'Experts',
  REASON_NOT_ANY: 'Cap',
  REASON_OTHERS: 'Altres',
  REASON_RADIO_NO: 'No',
  REASON_RADIO_YES: 'Sí',
  REASON_SELECT_LABEL: "Especifica el tipus d'explicació",
  REASON_TOGGLE_LABEL: "Expressa una raó que justifica l'opinió",
  SIGNIN: 'Login',
  SIGNIN_PASSWORD_HINT: '123456',
  SIGNIN_PASSWORD_LABEL: 'paraula de pas',
  SIGNIN_USER_HINT: 'user@server.com',
  SIGNIN_USER_LABEL: 'user',
  SIGNOUT: 'Desconnectar',
  SIGNUP: 'Crear',
  SIGNUP_PASSWORD_LABEL: 'paraula de pas',
  SIGNUP_USER: 'Crer usuari',
  SIGNUP_USERNAME_LABEL: "nom d'usuari",
  SIGNUP_USER_LABEL: 'adreça electrònica',
  TABLEEVALUATIONS_CONN_END: 'conn. fin',
  TABLEEVALUATIONS_CONN_EXPLANTIONS: 'conn. explicacions',
  TABLEEVALUATIONS_CONN_REASONS: 'conn. raons',
  TABLEEVALUATIONS_CONN_THESIS: 'conn. tesis',
  TABLEEVALUATIONS_EMAIL: 'email',
  TABLEEVALUATIONS_END_CONCLUSION: 'Conclusió',
  TABLEEVALUATIONS_END_EXTENSIVE: 'conclusió ext',
  TABLEEVALUATIONS_END_SYNTHETIC: 'conclusió sin',
  TABLEEVALUATIONS_END_THESIS: 'conclusió tesis',
  TABLEEVALUATIONS_END_TYPE_CONCLUSION: 'Tipus conclusió',
  TABLEEVALUATIONS_EXP_EVIDENCE: 'expl. evidència',
  TABLEEVALUATIONS_EXP_EXAMPLE: 'expl. exemple',
  TABLEEVALUATIONS_EXP_EXPANSION: 'expl. expansió',
  TABLEEVALUATIONS_EXP_EXPERT: 'exp. experts',
  TABLEEVALUATIONS_INTRODUCTION: 'introducció',
  TABLEEVALUATIONS_REASONS: 'raons',
  TABLEEVALUATIONS_TEXT_ID: 'id',
  TABLEEVALUATIONS_THESIS: 'Tesis',
  TABLETEXTS_GENDER: 'Gènere',
  TABLETEXTS_ID: 'Id',
  TABLETEXTS_LEVEL: 'Nivel',
  TABLETEXTS_NORMALIZED: 'Normalizado',
  TABLETEXTS_ORIGINAL: 'Original',
  TABLETEXTS_ROOM: 'Classe',
  TABLETEXTS_SCHOOL: 'Centre',
  TABLETEXTS_STUDENT: 'Estudiant',
  TABLETEXTS_TIME: 'Timepoint',
  TABLETEXTS_TIP: 'Consejo: pulsa mayúsculas to ordenar dos columnas',
  TABLETEXT_EVALUATIONS: 'Avaluacions',
  TABLE_QUALITY_EVALUATION_EVALUATOR: 'Avaluador',
  TABLE_QUALITY_EVALUATION_ID_FILE: 'ID Fitxer',
  TABLE_QUALITY_EVALUATION_QUALITY: 'Qualitat',
  TABLE_QUALITY_TIP: 'Consejo: pulsa mayúsculas to ordenar dos columnas',
  TABLE_SKIPS_EVALUATIONS_ID_FILE: 'ID fitxer',
  TABLE_SKIPS_EVALUATIONS_QUALITY: 'Qualitat',
  TABLE_SKIPS_EVALUATIONS_STRUCTURE: 'Estructura',
  TABLE_TEXTS_WITHOUT_QUALITY_EVALUATION_ID_FILE: 'ID fitxer',
  TABLE_TEXTS_WITHOUT_QUALITY_TIP: 'Consejo: pulsa mayúsculas to ordenar dos columnas', // eslint-disable-line
  UPLOADER_CLAIM: 'Arrossega textos aquí o clica',
  UPLOADER_PROMPT: 'Arrossega consignes aquí o clica',
  UPLOADER_TITLE_MODAL: 'Afegir',
  UPLOADTEXT_TITLE: 'Pujar textos per normalitzar'
}
