module.exports = {
  ADMINTEXT_TITLE: 'Administrar textos',
  ADMIN_EVALUATION: 'Administrar evaluaciones',
  ADMIN_EVALUATIONS_QUALITY_TITLE: 'Evaluaciones de calidad',
  ADMIN_EVALUATIONS_STUCTURE_TITLE: 'Evaluaciones de estructura',
  ADMIN_TEXTS: 'Administrar textos',
  APP_NAME: 'UABTexthandler',
  CANVASTEXTO_STUDENT: 'Estudiante',
  HOME_ALERT_ERROR_TITLE: 'Algunos campos están incompletos',
  HOME_LOOKING_TEXTS: 'Buscando texto para evaluar',
  HOME_QUESTIONS: 'Cuestionario',
  HOME_TEXT: 'Texto',
  LAYOUT_EVALUATION_CANVAS_LOOKING_TEXTS: 'Buscando texto para evaluar',
  LAYOUT_EVALUATION_QUIZ_BUTTON_SAVE: 'Guardar y seguir',
  LAYOUT_EVALUATION_QUIZ_BUTTON_SKIP: 'Saltar texto',
  LOGGED_MENU_QUALITY_EVALUATION: 'Evaluar calidad',
  LOGGED_MENU_STRUCTURE_EVALUATION: 'Evaluar estructura',
  QUALITY_QUIZ_NUMBER_SELECTR_LABEL: 'Calidad del texto',
  QUALITY_QUIZ_OPTION_FOURTH_PRIMARY: 'Cuarto de primaria',
  QUALITY_QUIZ_OPTION_SECOND_ESO: 'Segundo de la ESO',
  QUALITY_QUIZ_OPTION_SECOND_PRIMARY: 'Segundo de primaria',
  QUALITY_QUIZ_SELECT_GRADE: 'Selecciona un curso',
  QUIZ_CONCLUSION: '¿Tiene conectores de conclusion?',
  QUIZ_EXTENSIVE: '¿Tiene resumen extensivo?',
  QUIZ_FREE_TEXT_HINT: '(opcional)',
  QUIZ_FREE_TEXT_LABEL: 'Comentario libre',
  QUIZ_INTRODUCTION: '¿Tiene introduccion?',
  QUIZ_OPINION: '¿Tiene opinion?',
  QUIZ_OPINION_CONECTOR: '¿Tiene conector de opinion?',
  QUIZ_OPINION_OTHER_TYPE: '¿Tiene opinion de otro tipo?',
  QUIZ_OTHER_CONECTORS: '¿Tiene otors conectores?',
  QUIZ_REASON: 'Razón',
  QUIZ_REASON_CONECTORS: '¿Número de conectores de razón?',
  QUIZ_REASON_EXPLICATION: '¿Conectores de explicación?',
  QUIZ_SYNTHETIC: '¿Tiene resumen sintético?',
  RADIOBUTTONGROUP_RADIO_NO: 'No',
  RADIOBUTTONGROUP_RADIO_YES: 'Sí',
  REASON_ADD_TYPE: 'Añadir otro tipo',
  REASON_EVIDENCES: 'Evidencias',
  REASON_EXAMPLE: 'Ejemplo',
  REASON_EXPERTS: 'Expertos',
  REASON_NOT_ANY: 'Ninguna',
  REASON_OTHERS: 'Otros',
  REASON_RADIO_NO: 'No',
  REASON_RADIO_YES: 'Sí',
  REASON_SELECT_LABEL: 'Especifica el tipo de explicación',
  REASON_TOGGLE_LABEL: 'Expresa una razón que justifica la opinión',
  SIGNIN: 'Login',
  SIGNIN_PASSWORD_HINT: '123456',
  SIGNIN_PASSWORD_LABEL: 'contraseña',
  SIGNIN_USER_HINT: 'user@server.com',
  SIGNIN_USER_LABEL: 'user',
  SIGNOUT: 'desconectar',
  SIGNUP: 'Crear',
  SIGNUP_PASSWORD_LABEL: 'contraseña',
  SIGNUP_USER: 'Create usuario',
  SIGNUP_USERNAME_LABEL: 'nombre de usuario',
  SIGNUP_USER_LABEL: 'correo electrónico',
  TABLEEVALUATIONS_CONN_END: 'conn. fin',
  TABLEEVALUATIONS_CONN_EXPLANTIONS: 'conn. explicasiones',
  TABLEEVALUATIONS_CONN_REASONS: 'conn. razones',
  TABLEEVALUATIONS_CONN_THESIS: 'conn. tesis',
  TABLEEVALUATIONS_EMAIL: 'email',
  TABLEEVALUATIONS_END_EXTENSIVE: 'end. extensivo',
  TABLEEVALUATIONS_END_SYNTHETIC: 'end. sintético',
  TABLEEVALUATIONS_END_THESIS: 'end. tesis',
  TABLEEVALUATIONS_EXP_EVIDENCE: 'exp. evidencia',
  TABLEEVALUATIONS_EXP_EXAMPLE: 'exp. ejemplo',
  TABLEEVALUATIONS_EXP_EXPANSION: 'exp. expansión',
  TABLEEVALUATIONS_EXP_EXPERT: 'exp. experto',
  TABLEEVALUATIONS_INTRODUCTION: 'introducción',
  TABLEEVALUATIONS_REASONS: 'razones',
  TABLEEVALUATIONS_TEXT_ID: 'id',
  TABLEEVALUATIONS_THESIS: 'Tesis',
  TABLETEXTS_GENDER: 'Género',
  TABLETEXTS_ID: 'Id',
  TABLETEXTS_LEVEL: 'Nivel',
  TABLETEXTS_NORMALIZED: 'Normalizado',
  TABLETEXTS_ORIGINAL: 'Original',
  TABLETEXTS_ROOM: 'Clase',
  TABLETEXTS_SCHOOL: 'Escuela',
  TABLETEXTS_STUDENT: 'Estudiante',
  TABLETEXTS_TIME: 'Periodo',
  TABLETEXTS_TIP: 'Consejo: pulsa mayúsculas to ordenar dos columnas',
  TABLETEXT_EVALUATIONS: 'Evaluaciones',
  TABLE_QUALITY_EVALUATION_EVALUATOR: 'evaluador',
  TABLE_QUALITY_EVALUATION_ID_FILE: 'ID Fichero',
  TABLE_QUALITY_EVALUATION_QUALITY: 'Calidad',
  TABLE_QUALITY_TIP: 'Consejo: pulsa mayúsculas to ordenar dos columnas',
  UPLOADER_CLAIM: 'Arrastra ficheros aquí o clíca',
  UPLOADER_TITLE_MODAL: 'Agregar',
  UPLOADTEXT_TITLE: 'Subir textos para normalizar'
}
