module.exports = {
  ADMINTEXT_TITLE: 'Administrar textos',
  ADMIN_TEXTS: 'Administrar textos',
  APP_NAME: 'UABTexthandler',
  SIGNIN: 'Login',
  SIGNIN_PASSWORD_HINT: '123456',
  SIGNIN_PASSWORD_LABEL: 'contraseña',
  SIGNIN_USER_HINT: 'user@server.com',
  SIGNIN_USER_LABEL: 'user',
  SIGNOUT: 'desconectar',
  SIGNUP: 'Crear',
  SIGNUP_PASSWORD_LABEL: 'contraseña',
  SIGNUP_USER: 'Create usuario',
  SIGNUP_USERNAME_LABEL: 'nombre de usuario',
  SIGNUP_USER_LABEL: 'correo electrónico',
  TABLETEXTS_GENDER: 'Género',
  TABLETEXTS_ID: 'Id',
  TABLETEXTS_LEVEL: 'Nivel',
  TABLETEXTS_NORMALIZED: 'Normalizado',
  TABLETEXTS_ORIGINAL: 'Original',
  TABLETEXTS_ROOM: 'Clase',
  TABLETEXTS_SCHOOL: 'Escuela',
  TABLETEXTS_STUDENT: 'Estudiante',
  TABLETEXTS_TIME: 'Periodo',
  TABLETEXTS_TIP: 'Consejo: pulsa mayúsculas to ordenar dos columnas',
  TABLETEXT_EVALUATIONS: 'Evaluaciones',
  UPLOADER_CLAIM: 'Arrastra ficheros aquí o clíca',
  UPLOADER_TITLE_MODAL: 'Agregar',
  UPLOADTEXT_TITLE: 'Subir textos para normalizar'
}
